/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_dot_its_jpo_sdcsdw_PerXerCodec */

#ifndef _Included_gov_dot_its_jpo_sdcsdw_PerXerCodec
#define _Included_gov_dot_its_jpo_sdcsdw_PerXerCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_dot_its_jpo_sdcsdw_PerXerCodec
 * Method:    nativeGetAdvisorySituationDataType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_PerXerCodec_nativeGetAdvisorySituationDataType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_PerXerCodec
 * Method:    nativeGetServiceRequestType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_PerXerCodec_nativeGetServiceRequestType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_PerXerCodec
 * Method:    nativeGetServiceResponseType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_PerXerCodec_nativeGetServiceResponseType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_PerXerCodec
 * Method:    nativeGetDataRequestType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_PerXerCodec_nativeGetDataRequestType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_PerXerCodec
 * Method:    nativeGetAdvisorySituationDataDistributionType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_PerXerCodec_nativeGetAdvisorySituationDataDistributionType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_PerXerCodec
 * Method:    nativeGetDataAcceptanceType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_PerXerCodec_nativeGetDataAcceptanceType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_PerXerCodec
 * Method:    nativeGetDataReceiptType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_PerXerCodec_nativeGetDataReceiptType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_PerXerCodec
 * Method:    nativePerToXer
 * Signature: (I[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_PerXerCodec_nativePerToXer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_PerXerCodec
 * Method:    nativeXerToPer
 * Signature: (ILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_PerXerCodec_nativeXerToPer
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
