/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_dot_its_jpo_sdcsdw_PerXerCodec_Asn1Type */

#ifndef _Included_gov_dot_its_jpo_sdcsdw_PerXerCodec_Asn1Type
#define _Included_gov_dot_its_jpo_sdcsdw_PerXerCodec_Asn1Type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
