/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native */

#ifndef _Included_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native
#define _Included_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native
 * Method:    getAdvisorySituationDataType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native_getAdvisorySituationDataType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native
 * Method:    getServiceRequestType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native_getServiceRequestType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native
 * Method:    getServiceResponseType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native_getServiceResponseType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native
 * Method:    getDataRequestType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native_getDataRequestType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native
 * Method:    getAdvisorySituationDataDistributionType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native_getAdvisorySituationDataDistributionType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native
 * Method:    getDataAcceptanceType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native_getDataAcceptanceType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native
 * Method:    getDataReceiptType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native_getDataReceiptType
  (JNIEnv *, jclass);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native
 * Method:    perToXer
 * Signature: (I[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native_perToXer
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native
 * Method:    xerToPer
 * Signature: (ILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_gov_dot_its_jpo_sdcsdw_asn1_perxercodec_Native_xerToPer
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
